### ISSUE TITLE
[FEAT] detail view 구성하기

### ISSUE THREAD

**Issue by L-j-h-c** [SOPT-29th-Joint-Seminar-2/LOM-iOS#2]
## 📌  Feature Issue
밀리의 서재 detail view UI 구현하기

## 📝  To-do
- [x] 스크롤 뷰 구현 및 UI View 이용 구획화
- [ ] segmented control 기능 구현
- [ ] bookInfo 구조체 작성 + 데이터 받기
- [ ] 서버 연동 대비해서 작업하기(id)
