### ISSUE TITLE
[FEAT] : detail view UI에 API 연결하기

### ISSUE THREAD

**Issue by L-j-h-c** [SOPT-29th-Joint-Seminar-2/LOM-iOS#8]
## 📌  Feature Issue
밀리의 서재 detail view UI에 API 연결하기

## 📝  To-do
- [ ] 한줄리뷰 POST 구현
- [ ] 좋아요 POST 구현
- [x] 책 정보 GET 구현
